import type { DesignSettings } from "@/lib/store";

// Snapshot dos tokens de design "de fábrica" — deve espelhar exactamente
// o objecto `design` inicial em src/lib/store.ts (função `seed`).
// Usado para o botão "Restaurar personalização default".
export const DESIGN_DEFAULTS: DesignSettings = Object.freeze({
  modo: "light",
  accent: "0.72 0.06 230",
  sidebarBg: "0.25 0.025 258",
  raio: 0.625,
  densidade: "confortavel",
  nomeNegocio: "Atelier Tricotin",
  precoHoraBase: 12,
  idioma: "pt",
  pinContas: "0000",
  toqueAlarme: "ping",
  imagemFundo: "",
  fundoOpacidade: 0.85,
  fonteTitulos: "Sora, system-ui, sans-serif",
  corTitulos: "",
  fonteTexto: "Manrope, system-ui, sans-serif",
  corTexto: "",
  fonteMenu: "Manrope, system-ui, sans-serif",
  corMenu: "",
  corMenuAtivo: "",
  corMenuAtivoTexto: "",
  fonteAbas: "Manrope, system-ui, sans-serif",
  fonteCabecalho: "'Playfair Display', serif",
  corAbas: "",
  corAbaAtiva: "",
  corFundo: "",
  corCard: "",
  corBorda: "",
  corBotao: "",
  corBotaoTexto: "",
  corBotaoSecundario: "",
  corBotaoSecundarioTexto: "",
  corBotaoOutline: "",
  corBotaoOutlineTexto: "",
  corCabecalhoFundo: "",
  corCabecalhoIcone: "",
  corMuted: "",
  fontSizeBase: 16,
  fontSizeTitulos: 20,
  fontSizeTexto: 14,
  fontSizeMenu: 14,
  fontSizeAbas: 14,
  amazonMusicUrl: "",
  sidebarL: undefined,
  sidebarC: undefined,
  sidebarH: undefined,
  sidebarContraste: undefined,
  janelasOpacidade: 1,
  botaoPrimarioOpacidade: 1,
  botaoSecundarioOpacidade: 1,
  botaoOutlineOpacidade: 1,
  corAlertaFundo: "",
  corAlertaTexto: "",
  fontesPorPagina: {},
  spotifyClientId: "",
} as DesignSettings);