export const FONTS = [
  { name: "Sora", v: "Sora, system-ui, sans-serif" },
  { name: "Manrope", v: "Manrope, system-ui, sans-serif" },
  { name: "Quicksand", v: "Quicksand, system-ui, sans-serif" },
  { name: "Caveat", v: "Caveat, cursive" },
  { name: "Sistema", v: "system-ui, sans-serif" },
  { name: "Serifa", v: "Georgia, 'Times New Roman', serif" },
  { name: "Mono", v: "ui-monospace, SFMono-Regular, Menlo, monospace" },
  { name: "Playfair Display", v: "'Playfair Display', serif" },
  { name: "Merriweather", v: "Merriweather, serif" },
  { name: "Lora", v: "Lora, serif" },
  { name: "Nunito", v: "Nunito, sans-serif" },
  { name: "Poppins", v: "Poppins, sans-serif" },
  { name: "Roboto", v: "Roboto, sans-serif" },
  { name: "Open Sans", v: "'Open Sans', sans-serif" },
  { name: "Montserrat", v: "Montserrat, sans-serif" },
  { name: "Raleway", v: "Raleway, sans-serif" },
  { name: "Oswald", v: "Oswald, sans-serif" },
  { name: "Bebas Neue", v: "'Bebas Neue', sans-serif" },
  { name: "Dancing Script", v: "'Dancing Script', cursive" },
  { name: "Pacifico", v: "Pacifico, cursive" },
  { name: "Great Vibes", v: "'Great Vibes', cursive" },
  { name: "Josefin Sans", v: "'Josefin Sans', sans-serif" },
  { name: "Rubik", v: "Rubik, sans-serif" },
  { name: "Work Sans", v: "'Work Sans', sans-serif" },
  { name: "DM Sans", v: "'DM Sans', sans-serif" },
  { name: "Fira Sans", v: "'Fira Sans', sans-serif" },
  { name: "Space Grotesk", v: "'Space Grotesk', sans-serif" },
];