/**
 * Base de 300 frases motivacionais para o atelier.
 * Cada frase tem categoria (para filtros) e emojis temáticos obrigatórios.
 */
export type FraseCategoria =
  | "foco"
  | "saude"
  | "costura"
  | "croche"
  | "tricotin"
  | "criatividade"
  | "geral";

export interface Frase {
  id: string;
  texto: string;
  categoria: FraseCategoria;
  emojis: string; // pré-formatado, sempre presente
}

const f = (id: number, texto: string, categoria: FraseCategoria, emojis: string): Frase => ({
  id: `f${id}`,
  texto,
  categoria,
  emojis,
});

export const FRASES_BASE: Frase[] = [
  // ── FOCO (1-50) ──
  f(1, "Um ponto de cada vez. É assim que se constrói um atelier inteiro.", "foco", "✨"),
  f(2, "Hoje não precisa ser perfeito, só precisa começar.", "foco", "💡"),
  f(3, "Respira fundo, pega na agulha e confia no processo.", "foco", "🪡"),
  f(4, "Pequenos progressos diários valem mais do que dias perfeitos.", "foco", "🌟"),
  f(5, "Concentra-te no fio que tens na mão, não no novelo todo.", "foco", "🧶"),
  f(6, "O que ontem parecia difícil, hoje é só mais uma carreira.", "foco", "💪"),
  f(7, "Foco não é fazer tudo, é fazer o que importa agora.", "foco", "🎯"),
  f(8, "A pressa estraga mais peças do que a falta de talento.", "foco", "🕰️"),
  f(9, "Escolhe uma tarefa, termina-a e celebra. Repete.", "foco", "✅"),
  f(10, "Silencia o ruído, abraça o ritmo do teu trabalho.", "foco", "🤫"),
  f(11, "A produtividade verdadeira é fazer com calma o que importa.", "foco", "🧘"),
  f(12, "Um molde por dia. Uma peça por semana. Um ano transformado.", "foco", "📅"),
  f(13, "O teu tempo de atelier é sagrado — protege-o.", "foco", "🕯️"),
  f(14, "Hoje é um excelente dia para acabar aquela peça parada.", "foco", "🏁"),
  f(15, "Disciplina é o amor pela tua arte traduzido em hábito.", "foco", "💛"),
  f(16, "Não desfaças tudo por causa de um ponto torto. Continua.", "foco", "🪡"),
  f(17, "Acaba antes de começar mais. O atelier agradece.", "foco", "📦"),
  f(18, "Lista curta, mãos ocupadas, coração leve.", "foco", "📝"),
  f(19, "Faz pouco, mas faz bem feito. É a tua assinatura.", "foco", "✍️"),
  f(20, "A constância vence o talento que não trabalha.", "foco", "🔁"),
  f(21, "Define a próxima carreira. Só essa. E avança.", "foco", "➡️"),
  f(22, "O teu foco é o teu superpoder mais subestimado.", "foco", "⚡"),
  f(23, "Hoje, menos abas no telemóvel e mais pontos na agulha.", "foco", "📵"),
  f(24, "Concentra-te. O mundo pode esperar 25 minutos.", "foco", "⏳"),
  f(25, "Trabalha em blocos. Descansa em blocos. Floresce sempre.", "foco", "🌸"),
  f(26, "A tua maior concorrente és tu sem foco.", "foco", "🪞"),
  f(27, "Um atelier organizado começa por uma mente organizada.", "foco", "🧠"),
  f(28, "Não saltes de projeto em projeto. Mergulha num.", "foco", "🌊"),
  f(29, "O foco transforma horas em obras.", "foco", "🎨"),
  f(30, "Liga uma vela, prepara o chá, e dedica-te.", "foco", "🕯️"),
  f(31, "Adia o telemóvel, abraça a agulha.", "foco", "🪡"),
  f(32, "Uma tarefa terminada vale mais do que dez começadas.", "foco", "🏆"),
  f(33, "Faz hoje o ponto que o teu eu de amanhã agradecerá.", "foco", "🙏"),
  f(34, "O segredo não é fazer rápido, é fazer todos os dias.", "foco", "📆"),
  f(35, "Aceita o ritmo lento — é nele que mora a qualidade.", "foco", "🐢"),
  f(36, "Foco é escolher o que vais deixar por fazer hoje.", "foco", "✂️"),
  f(37, "Trabalha com intenção, descansa com permissão.", "foco", "🌿"),
  f(38, "Um ambiente arrumado liberta a tua criatividade.", "foco", "🧺"),
  f(39, "Define o objetivo da sessão antes de pegar na agulha.", "foco", "🎯"),
  f(40, "Pequenos rituais antes de começar mudam tudo.", "foco", "🍵"),
  f(41, "Faz uma coisa de cada vez — e fá-la com alma.", "foco", "💛"),
  f(42, "Trabalha como artesã, descansa como rainha.", "foco", "👑"),
  f(43, "Não confundas estar ocupada com estar a progredir.", "foco", "🧭"),
  f(44, "Hoje vais conseguir mais do que pensas. Começa.", "foco", "🚀"),
  f(45, "O foco protege a tua energia criativa.", "foco", "🔋"),
  f(46, "Mantém-te presente: cada ponto merece a tua atenção.", "foco", "🪡"),
  f(47, "O atelier dos teus sonhos constrói-se em sessões focadas.", "foco", "🏡"),
  f(48, "Acolhe a tarefa difícil primeiro. O resto será doce.", "foco", "🍯"),
  f(49, "O melhor momento para avançar é exatamente agora.", "foco", "⏱️"),
  f(50, "Concentra-te no fio. O resto resolve-se.", "foco", "🧵"),

  // ── SAÚDE / PAUSA (51-100) ──
  f(51, "Cuida das tuas mãos como cuidas das tuas peças — alonga, respira, hidrata.", "saude", "🖐️ 💧"),
  f(52, "Pousa a agulha. Bebe água. O teu corpo é o teu primeiro atelier.", "saude", "💧 🌸"),
  f(53, "Cinco minutos de alongamento valem por uma hora extra de produtividade.", "saude", "🧘‍♀️"),
  f(54, "Rola os ombros, gira os pulsos. O teu corpo merece carinho.", "saude", "💪"),
  f(55, "Pisca os olhos com intenção. Olha para longe. Volta com clareza.", "saude", "👁️ 🌿"),
  f(56, "Levanta-te a cada hora. O sangue precisa de viajar tanto como a tua imaginação.", "saude", "🚶‍♀️"),
  f(57, "Respira: 4 segundos a inspirar, 6 a expirar. Reseta tudo.", "saude", "🌬️"),
  f(58, "Estica os dedos como se fossem pétalas a abrir.", "saude", "🌸"),
  f(59, "Uma chávena quente, uma janela aberta, um suspiro. Pausa.", "saude", "☕ 🌬️"),
  f(60, "O teu pescoço também trabalha contigo. Roda-o devagar.", "saude", "🧘"),
  f(61, "Hidrata-te. O cérebro criativo precisa de água.", "saude", "💧 🧠"),
  f(62, "Faz uma pausa antes de precisares dela.", "saude", "🌿"),
  f(63, "Os teus pulsos pedem um intervalo carinhoso.", "saude", "🖐️"),
  f(64, "Música suave, alongamento curto, café morno. Receita perfeita.", "saude", "🎶 ☕"),
  f(65, "Cinco respirações profundas mudam o teu dia.", "saude", "🌬️ 💚"),
  f(66, "Levanta os braços ao céu. Solta o que pesa.", "saude", "🙆‍♀️"),
  f(67, "Bebe um copo de água por cada hora de tricô.", "saude", "💧"),
  f(68, "O teu corpo é a tua ferramenta principal. Mantém-no afiado.", "saude", "💪"),
  f(69, "Pausa para olhar pela janela. A natureza cura.", "saude", "🌿"),
  f(70, "Massaja as mãos com creme. Trata-as como joias.", "saude", "🖐️ 🌸"),
  f(71, "Boa postura agora, costas felizes amanhã.", "saude", "🪑"),
  f(72, "Escuta o teu corpo antes que ele grite.", "saude", "💚"),
  f(73, "Uma soneca curta vale mais do que um café duplo.", "saude", "😴"),
  f(74, "Respira pelo nariz. Solta tudo pela boca.", "saude", "🌬️"),
  f(75, "Para. Bebe. Respira. Continua mais forte.", "saude", "💧 💚"),
  f(76, "A pausa não é preguiça, é manutenção.", "saude", "🌿"),
  f(77, "Caminhar dez minutos é terapia gratuita.", "saude", "🚶‍♀️ 🌿"),
  f(78, "Aquece o pescoço com a mão. Pequeno gesto, grande alívio.", "saude", "🖐️"),
  f(79, "Cuida da luz onde trabalhas. Os teus olhos agradecem.", "saude", "💡 👁️"),
  f(80, "O chá de hoje sabe melhor se for bebido com calma.", "saude", "🍵"),
  f(81, "Estica a coluna como se quisesses tocar o teto.", "saude", "🙆‍♀️"),
  f(82, "Faz uma pausa sem culpa. Trabalhaste bem.", "saude", "💚"),
  f(83, "O sono é o teu melhor designer.", "saude", "😴 ✨"),
  f(84, "Aromas suaves no atelier acalmam o sistema nervoso.", "saude", "🌸"),
  f(85, "Os teus olhos pedem um foco distante. Olha pela janela.", "saude", "👁️ 🌿"),
  f(86, "A cada hora, levanta-te e move o corpo.", "saude", "💪"),
  f(87, "Ouve o teu corpo: cansaço também é sabedoria.", "saude", "🧠 💚"),
  f(88, "Uma sessão de respiração equivale a uma chávena de calma.", "saude", "🌬️ ☕"),
  f(89, "Estica as costas, abre o peito, sente o ar.", "saude", "🌬️"),
  f(90, "Bebe água com intenção. É amor próprio em líquido.", "saude", "💧"),
  f(91, "Descansar é parte do criar. Honra essa verdade.", "saude", "🌿"),
  f(92, "Faz alongamentos de pulsos antes e depois de tricotar.", "saude", "🖐️"),
  f(93, "Pausa de cinco minutos > dor de dez horas.", "saude", "💚"),
  f(94, "O atelier também precisa de respirar contigo.", "saude", "🌬️ 🌸"),
  f(95, "Cuida do teu corpo. Ele aguenta tudo o que sonhas.", "saude", "💪 💚"),
  f(96, "Olhos cansados pedem 20 segundos a olhar para o longe.", "saude", "👁️"),
  f(97, "A tua saúde mental vale mais do que qualquer encomenda.", "saude", "🧠 💚"),
  f(98, "Sai do atelier por uns minutos. Volta inspirada.", "saude", "🚶‍♀️ ✨"),
  f(99, "Uma boa pausa multiplica a tua próxima hora.", "saude", "🌿"),
  f(100, "Cuidar de ti é cuidar do teu negócio.", "saude", "💚 🌸"),

  // ── COSTURA (101-140) ──
  f(101, "Cada costura é um abraço invisível em quem vai usar a peça.", "costura", "🪡 🧵"),
  f(102, "O alinhavo é a promessa. O ponto firme é o compromisso.", "costura", "🪡"),
  f(103, "A linha certa salva qualquer tecido difícil.", "costura", "🧵"),
  f(104, "Mede duas vezes, corta uma. Sempre.", "costura", "📏 ✂️"),
  f(105, "O tecido fala — só precisas de o saber ouvir.", "costura", "🧵"),
  f(106, "Costurar é meditar com as mãos.", "costura", "🪡 🧘"),
  f(107, "Cada bainha bem feita é uma carta de amor à peça.", "costura", "💌 🪡"),
  f(108, "Os bastidores ensinam-te a paciência.", "costura", "✂️"),
  f(109, "Não há ponto invisível, só ponto bem dado.", "costura", "🪡"),
  f(110, "O ferro é o teu melhor amigo silencioso.", "costura", "♨️"),
  f(111, "Escolhe a agulha certa e o tecido obedece.", "costura", "🪡"),
  f(112, "Costura devagar, descose menos.", "costura", "🐢 🧵"),
  f(113, "Um molde bem cortado é meia peça pronta.", "costura", "✂️ 📐"),
  f(114, "A linha combinada é elegância silenciosa.", "costura", "🧵"),
  f(115, "O alfaiate em ti nasce do detalhe.", "costura", "🪡 ✨"),
  f(116, "Cada peça que costuras conta a tua história.", "costura", "📖 🧵"),
  f(117, "Tecido difícil pede mãos calmas.", "costura", "🪡"),
  f(118, "Costurar é dar uma segunda vida ao pano.", "costura", "♻️ 🧵"),
  f(119, "O acabamento é a tua assinatura.", "costura", "✍️"),
  f(120, "Aprende a amar o avesso da peça — é onde mora a verdade.", "costura", "🪡"),
  f(121, "Os retalhos guardam histórias por terminar.", "costura", "🧵 ✨"),
  f(122, "Costura com música. O ritmo afina o ponto.", "costura", "🎶 🪡"),
  f(123, "Cada zíper bem colocado é uma vitória pequena.", "costura", "🪡"),
  f(124, "A simetria é elegância. Mas o feito à mão tem alma.", "costura", "💛 🧵"),
  f(125, "Costurar não é só técnica, é também ternura.", "costura", "💖 🪡"),
  f(126, "O viés bem feito disfarça mil imperfeições.", "costura", "🧵"),
  f(127, "Uma costureira atenta vê o que a máquina não conta.", "costura", "👁️ 🪡"),
  f(128, "Tens nas mãos o que a indústria não consegue replicar.", "costura", "🪡 ✨"),
  f(129, "Trata a tua máquina como uma parceira: alimenta-a com óleo e carinho.", "costura", "🛠️"),
  f(130, "Termina sempre o pespontamento com nó seguro.", "costura", "🧵"),
  f(131, "Costurar à mão é redescobrir a paciência.", "costura", "🪡 🌿"),
  f(132, "Não há tecido feio, há tecido sem propósito.", "costura", "🧵"),
  f(133, "Um botão bem pregado vale uma costura inteira.", "costura", "🔘 🪡"),
  f(134, "O ponto invisível é também o mais honesto.", "costura", "🪡"),
  f(135, "Costurar é unir o que parecia separado para sempre.", "costura", "🧵 💛"),
  f(136, "Quem costura, escreve histórias em tecido.", "costura", "📖 🪡"),
  f(137, "Confia no teu olhar. O traço da costura é teu.", "costura", "👁️"),
  f(138, "Atenção ao avesso. O cliente sente, mesmo sem ver.", "costura", "🪡 ✨"),
  f(139, "A linha forte segura sonhos por anos.", "costura", "🧵 💛"),
  f(140, "Costurar devagar é a forma mais rápida de fazer bem.", "costura", "🐢 🪡"),

  // ── CROCHÊ & AMIGURUMI (141-200) ──
  f(141, "Cada carreira é uma respiração. Conta-as devagar.", "croche", "🧶"),
  f(142, "Um amigurumi nasce de muita paciência e um sorriso.", "croche", "🧶 😊"),
  f(143, "O crochê ensina-te que tudo o que se enrola, também se solta.", "croche", "🧶"),
  f(144, "Os teus pontos altos contam histórias altas.", "croche", "🧶 ✨"),
  f(145, "Recheia com amor — sente-se no aperto do abraço.", "croche", "🧸 💛"),
  f(146, "A magia do amigurumi mora nos olhinhos bem alinhados.", "croche", "👀 🧸"),
  f(147, "Crochetar é tecer calma em forma de fio.", "croche", "🧶 🌿"),
  f(148, "Aumentos certos no início, mundo redondo perfeito.", "croche", "🧶"),
  f(149, "Cada novelo é uma promessa por cumprir.", "croche", "🧶 ✨"),
  f(150, "O teu primeiro anel mágico foi só o começo.", "croche", "🧶"),
  f(151, "Um amigurumi feito à mão é um amigo para a vida.", "croche", "🧸 💛"),
  f(152, "Conta os pontos como contas bênçãos.", "croche", "🧶 🙏"),
  f(153, "A textura do fio é metade da poesia.", "croche", "🧶"),
  f(154, "O crochê não tem pressa — e ensina-te o mesmo.", "croche", "🐢 🧶"),
  f(155, "Pontos errados também ensinam a desfazer com amor.", "croche", "🧶 💛"),
  f(156, "Os teus amigurumis ganham vida quando os olhos entram.", "croche", "👀 🧸"),
  f(157, "Uma carreira por sessão de chá é progresso suficiente.", "croche", "☕ 🧶"),
  f(158, "Crochetar é dizer 'eu cuido' em forma de peça.", "croche", "🧶 💛"),
  f(159, "Um amigurumi feito por ti vale por mil produzidos em série.", "croche", "🧸 ✨"),
  f(160, "A magia está nas mãos calmas, não nas agulhas caras.", "croche", "🧶"),
  f(161, "Mantém a tensão do fio constante — é o teu segredo.", "croche", "🧶"),
  f(162, "Cada amigurumi que fazes leva um pedaço do teu sorriso.", "croche", "🧸 😊"),
  f(163, "Tricota, croche, descansa, repete.", "croche", "🧶 🌿"),
  f(164, "O crochê é silêncio com forma.", "croche", "🤫 🧶"),
  f(165, "Faz uma carreira de cada vez. O bicho vai aparecer.", "croche", "🧸"),
  f(166, "A lã chora se a apertas demais. Solta-a um pouco.", "croche", "🧶"),
  f(167, "Os teus amigurumis são pequenos manifestos de ternura.", "croche", "🧸 💖"),
  f(168, "Crochetar é escrever poesia com fio.", "croche", "🧶 ✍️"),
  f(169, "O recheio é a alma do teu amigurumi.", "croche", "🧸"),
  f(170, "A agulha certa muda toda a peça.", "croche", "🧶"),
  f(171, "Não há mãos canhotas no crochê — só ritmos diferentes.", "croche", "🧶 💛"),
  f(172, "Aprende um ponto novo por mês. Tu floresces assim.", "croche", "🧶 🌸"),
  f(173, "Crochetar a céu aberto é terapia gratuita.", "croche", "🌿 🧶"),
  f(174, "Os teus pontos baixinhos seguram o mundo.", "croche", "🧶"),
  f(175, "Cada amigurumi é uma criatura nova no teu universo.", "croche", "🧸 ✨"),
  f(176, "Conta os pontos. Conta as bênçãos. É a mesma coisa.", "croche", "🧶 🙏"),
  f(177, "Os fios que sobram também merecem virar arte.", "croche", "🧶 ♻️"),
  f(178, "Crochê é o abraço que se faz com as mãos.", "croche", "🧶 🤗"),
  f(179, "O segredo do bom amigurumi é não desistir nos aumentos.", "croche", "🧸 💪"),
  f(180, "Faz pequenas séries. Mantém a alegria viva.", "croche", "🧶 😊"),
  f(181, "Os teus dedos sabem o caminho. Confia.", "croche", "🖐️ 🧶"),
  f(182, "A lã ensina-te que tudo pode ser refeito.", "croche", "🧶 ✨"),
  f(183, "Há paz numa carreira bem feita.", "croche", "🧶 🌿"),
  f(184, "O amigurumi que recheias hoje será o conforto de alguém amanhã.", "croche", "🧸 💛"),
  f(185, "Marca as carreiras. O teu eu futuro agradece.", "croche", "🧶 📍"),
  f(186, "Os teus amigurumis carregam a tua energia. Faz com amor.", "croche", "🧸 💖"),
  f(187, "Termina a carreira antes de pousar a agulha.", "croche", "🧶"),
  f(188, "O ponto baixo é humilde, mas constrói tudo.", "croche", "🧶 💛"),
  f(189, "Os erros do crochê viram ideias novas.", "croche", "🧶 ✨"),
  f(190, "A primeira peça nunca é a melhor. A décima já é tua.", "croche", "🧶"),
  f(191, "Crocheta em pé de vez em quando. O corpo agradece.", "croche", "🧶 🧍‍♀️"),
  f(192, "A roda mágica é o teu universo a começar.", "croche", "🧶 🌍"),
  f(193, "Recheia devagar. O formato decide-se aí.", "croche", "🧸"),
  f(194, "Faz testes de tensão antes do projeto grande.", "croche", "🧶 📏"),
  f(195, "Crochê é arte que se sente com os olhos fechados.", "croche", "🧶 ✨"),
  f(196, "Cada amigurumi merece um nome.", "croche", "🧸 💛"),
  f(197, "Os teus pontos são impressões digitais únicas.", "croche", "🧶"),
  f(198, "Recolhe-te no crochê quando o mundo for demais.", "croche", "🧶 🌿"),
  f(199, "Os teus dedos pintam com lã.", "croche", "🧶 🎨"),
  f(200, "Crocheta. Sorri. Repete. É tudo.", "croche", "🧶 😊"),

  // ── TRICOTIN (201-240) ──
  f(201, "O tricotin ensina a beleza do repetir com calma.", "tricotin", "🧶"),
  f(202, "Cada nó é uma micro-vitória.", "tricotin", "🧶 ✨"),
  f(203, "O tricotin em tela é pintura feita com fio.", "tricotin", "🎨 🧶"),
  f(204, "Um quadro de tricotin guarda horas de presença.", "tricotin", "🖼️ 🧶"),
  f(205, "A textura é o teu pincel.", "tricotin", "🧶 🎨"),
  f(206, "Tricotin é meditação em loop.", "tricotin", "🧘 🧶"),
  f(207, "Escolhe as cores como escolhes a tua manhã.", "tricotin", "🎨 ☀️"),
  f(208, "Um quadro pequeno hoje, um mural amanhã.", "tricotin", "🖼️"),
  f(209, "A paciência é o ingrediente secreto do tricotin.", "tricotin", "🧶 🌿"),
  f(210, "Faz tricotin enquanto ouves o teu podcast preferido.", "tricotin", "🎧 🧶"),
  f(211, "O fio certo muda toda a obra.", "tricotin", "🧶 ✨"),
  f(212, "O tricotin lembra-te que progresso pequeno é progresso real.", "tricotin", "🧶"),
  f(213, "Cada nó é um ponto de mindfulness.", "tricotin", "🧶 🧘"),
  f(214, "Trabalha com luz natural sempre que puderes.", "tricotin", "☀️ 🧶"),
  f(215, "O tricotin em quadro é arte que abraça paredes.", "tricotin", "🖼️ 💛"),
  f(216, "Cores quentes para dias frios. Confia no teu instinto.", "tricotin", "🎨"),
  f(217, "O ritmo do tricotin afina o pensamento.", "tricotin", "🧶 🧠"),
  f(218, "Cada projeto de tricotin é uma viagem lenta. Aproveita.", "tricotin", "🧶 🌿"),
  f(219, "A repetição é meditação ativa.", "tricotin", "🧶 🧘"),
  f(220, "Cria uma paleta antes de começar. Ganharás tempo.", "tricotin", "🎨 🧶"),
  f(221, "O tricotin ensina a presença sem barulho.", "tricotin", "🤫 🧶"),
  f(222, "Mais um nó. Sempre mais um nó.", "tricotin", "🧶 ✨"),
  f(223, "A textura é onde mora a alma da obra.", "tricotin", "🧶"),
  f(224, "Tricotin em tela é poesia visual.", "tricotin", "🎨 🧶"),
  f(225, "Escolhe um tema. Deixa as cores falarem.", "tricotin", "🎨"),
  f(226, "Os teus quadros vão durar décadas.", "tricotin", "🖼️ ✨"),
  f(227, "Tricotin pede uma cadeira confortável. Cuida disso.", "tricotin", "🪑 🧶"),
  f(228, "Os contrastes fazem a obra falar.", "tricotin", "🎨"),
  f(229, "Trabalha com música suave. O ritmo entra no fio.", "tricotin", "🎶 🧶"),
  f(230, "Não corras. O tricotin é gentileza com tempo.", "tricotin", "🐢 🧶"),
  f(231, "Os teus quadros são heranças. Assina-os.", "tricotin", "✍️ 🖼️"),
  f(232, "O tricotin floresce em mãos pacientes.", "tricotin", "🌸 🧶"),
  f(233, "Mais textura, menos pressa.", "tricotin", "🧶"),
  f(234, "Cada paleta conta uma estação do ano.", "tricotin", "🎨 🍂"),
  f(235, "A tela vazia é só uma promessa de cor.", "tricotin", "🖼️ ✨"),
  f(236, "O teu fio é tinta. Pinta com calma.", "tricotin", "🧶 🎨"),
  f(237, "Faz pausas para olhar à distância. A composição revela-se.", "tricotin", "👁️ 🖼️"),
  f(238, "Trabalha de cima para baixo. Ou de baixo para cima. Faz como te pede o coração.", "tricotin", "💛 🧶"),
  f(239, "Cada quadro de tricotin é um diário visual.", "tricotin", "🖼️ ✨"),
  f(240, "O tricotin é o teu retiro sem sair de casa.", "tricotin", "🏡 🧶"),

  // ── CRIATIVIDADE (241-275) ──
  f(241, "A inspiração mora em quem trabalha todos os dias.", "criatividade", "💡 ✨"),
  f(242, "Cria como ninguém estivesse a ver. Vende como todos estivessem.", "criatividade", "🎨"),
  f(243, "A originalidade nasce do compromisso, não do talento.", "criatividade", "✨"),
  f(244, "Copia para aprender. Cria para te encontrar.", "criatividade", "🎨"),
  f(245, "A tua marca é a tua história contada com fio.", "criatividade", "🧵 ✨"),
  f(246, "Não esperes pela musa. Senta-te e faz.", "criatividade", "💡"),
  f(247, "Erros são protótipos disfarçados.", "criatividade", "🎨 💡"),
  f(248, "Mistura técnicas. A magia mora nos cruzamentos.", "criatividade", "✨"),
  f(249, "Guarda um caderno de ideias sempre por perto.", "criatividade", "📓 ✏️"),
  f(250, "A tua próxima coleção começa com um esboço hoje.", "criatividade", "✏️ 🎨"),
  f(251, "A criatividade adora limites. Define-os.", "criatividade", "💡"),
  f(252, "Cria pequenas séries. Ganha velocidade e alma.", "criatividade", "🎨"),
  f(253, "O teu olhar é a tua maior vantagem competitiva.", "criatividade", "👁️ ✨"),
  f(254, "Faz testes pequenos. Lança rápido. Aprende sempre.", "criatividade", "💡"),
  f(255, "A inspiração é diária — basta abrires os olhos.", "criatividade", "👁️ 🌿"),
  f(256, "Brinca com cores fora da tua zona de conforto.", "criatividade", "🎨 ✨"),
  f(257, "Faz uma peça só para ti. A alma agradece.", "criatividade", "💛 🎨"),
  f(258, "O teu estilo nasce da repetição com intenção.", "criatividade", "✨"),
  f(259, "Combina materiais inesperados. Descobre tesouros.", "criatividade", "🎨"),
  f(260, "Inspira-te na natureza. Ela é a mestre maior.", "criatividade", "🌿 💡"),
  f(261, "A criatividade é músculo. Treina-a diariamente.", "criatividade", "💪 ✨"),
  f(262, "As tuas peças contam o que tu não dizes.", "criatividade", "💛 🎨"),
  f(263, "Olha para arte fora do teu nicho. Vais voltar diferente.", "criatividade", "🖼️ ✨"),
  f(264, "Hoje cria por prazer, amanhã por encomenda.", "criatividade", "🎨 💛"),
  f(265, "Coleciona texturas, cores, sons. Tudo vira atelier.", "criatividade", "✨"),
  f(266, "A tua intuição é dado de qualidade.", "criatividade", "💡"),
  f(267, "Inspirações novas pedem ambientes novos. Sai um pouco.", "criatividade", "🌿 ✨"),
  f(268, "A criatividade não tem horário, mas adora rotina.", "criatividade", "🕰️ 🎨"),
  f(269, "Cria com as mãos. Pensa com o coração.", "criatividade", "💛 🖐️"),
  f(270, "A tua marca cresce em cada peça única.", "criatividade", "✨ 🎨"),
  f(271, "Sê fiel ao teu universo. O cliente certo reconhece-o.", "criatividade", "💛"),
  f(272, "A imperfeição feita à mão é a nova elegância.", "criatividade", "🪡 ✨"),
  f(273, "Documenta o processo. É tão valioso quanto a peça.", "criatividade", "📷 🎨"),
  f(274, "Brinca. A criança em ti sabe o caminho.", "criatividade", "🧸 ✨"),
  f(275, "A tua criatividade salva-te em qualquer dia cinzento.", "criatividade", "🎨 💛"),

  // ── GERAL / NEGÓCIO (276-300) ──
  f(276, "Gerir um atelier a solo é coragem em forma de rotina.", "geral", "💪 ✨"),
  f(277, "Cobra o valor real da tua arte. Tu vales isso.", "geral", "💛 💶"),
  f(278, "Negócio que não descansa, não dura. Honra a tua pausa.", "geral", "🌿"),
  f(279, "Cliente bem tratado é a tua melhor campanha.", "geral", "💛"),
  f(280, "O preço justo protege o teu sonho.", "geral", "💶 ✨"),
  f(281, "Hoje é um ótimo dia para enviar aquela proposta.", "geral", "📩"),
  f(282, "Faz o ponto. Faz a venda. Faz a pausa.", "geral", "🪡 💛"),
  f(283, "Pequenos negócios mudam vidas — começando pela tua.", "geral", "✨"),
  f(284, "Organiza as contas com o mesmo amor que tens pelo fio.", "geral", "📒 💛"),
  f(285, "Um cliente fiel vale por dez novos.", "geral", "💛"),
  f(286, "Conta histórias com as tuas peças. Vende-se mais alma do que produto.", "geral", "📖 ✨"),
  f(287, "Investe em ti antes de investires em ferramentas.", "geral", "🌿 💛"),
  f(288, "A tua marca é maior do que tu pensas. Acredita.", "geral", "✨"),
  f(289, "Faz seguidores que te apoiam, não números vazios.", "geral", "💛"),
  f(290, "O teu Instagram é um portfolio. Trata-o assim.", "geral", "📱 🎨"),
  f(291, "Trata cada encomenda como se fosse a primeira.", "geral", "💛"),
  f(292, "Aprende a dizer não. O teu tempo é finito.", "geral", "🌿"),
  f(293, "Faz uma reunião contigo todas as semanas.", "geral", "📓 ✨"),
  f(294, "Negocia sem medo. Tu trazes valor à mesa.", "geral", "💪 💛"),
  f(295, "Marca a tua peça com cuidado. É a tua assinatura no mundo.", "geral", "✍️ ✨"),
  f(296, "Faz amizades com outras artesãs. Crescem todas juntas.", "geral", "🤝 💛"),
  f(297, "Hoje é um bom dia para celebrar quanto já cresceste.", "geral", "🎉 ✨"),
  f(298, "Diversifica produtos. Diversifica horários. Não diversifiques valores.", "geral", "💛"),
  f(299, "A persistência é a tua superpotência mais valiosa.", "geral", "💪 ✨"),
  f(300, "És artesã, empresária e poetisa do fio. Honra os três.", "geral", "🧶 💛 ✨"),
];

export const CATEGORIA_LABEL: Record<FraseCategoria, string> = {
  foco: "Foco",
  saude: "Saúde / Pausa",
  costura: "Costura",
  croche: "Crochê / Amigurumi",
  tricotin: "Tricotin",
  criatividade: "Criatividade",
  geral: "Geral",
};

export const TAGS_FILTRO: Array<{ key: "todas" | FraseCategoria; label: string }> = [
  { key: "todas", label: "Todas" },
  { key: "foco", label: "Foco" },
  { key: "saude", label: "Saúde / Pausa" },
  { key: "costura", label: "Costura" },
  { key: "croche", label: "Crochê / Amigurumi" },
  { key: "tricotin", label: "Tricotin" },
  { key: "criatividade", label: "Criatividade" },
];