import type { Idioma } from "./store";

export const splashPhrases: Record<Idioma, string[]> = {
  pt: [
    "Recortando o tecido para costurar...",
    "Enfiando a linha na agulha de coser...",
    "Organizando novelos de várias cores...",
    "Procurando o tamanho ideal de agulha para o projeto...",
    "Ajustando a tensão do fio no tricotin...",
    "Contando os pontos do amigurumi...",
    "Contornando o risco do bordado livre...",
    "A moldar o arame para o próximo tricotin...",
    "Preparando a meada de ponto cruz...",
    "Enchendo o amigurumi com amor e fibra...",
    "Desenhando as curvas do molde de costura...",
    "Contando cruzinhas no tecido Aida...",
    "Passando o risco do desenho para o linho...",
    "A aquecer as mãos para tricotar...",
    "Escolhendo a palete de cores perfeita...",
    "Enchendo a bobine com a linha de costura...",
    "Desfazendo um nó cego no novelo...",
    "Terminando a última carreira do projeto...",
    "Preparando o bastidor para começar a bordar...",
    "Alinhando o viés na borda do tecido...",
    "A fechar os pontos invisíveis do amigurumi...",
    "Calculando os centímetros de arame necessários...",
    "Esboçando uma nova receita de crochê...",
    "Organizando a caixinha de meadas por códigos...",
    "Ajustando o ponto da máquina de costura...",
    "Nivelando a pauta de caligrafia para o tricotin...",
    "Verificando os códigos DMC no stock...",
    "Dando o nó final para prender o bordado...",
    "Esticando o tecido para ficar bem firme...",
    "Criando magia com linhas, fios e agulhas...",
    "Escondendo a ponta do fio para o acabamento perfeito...",
    "Dando vida ao desenho através do ponto cruz...",
    "Alfinetando o molde ao tecido com precisão...",
    "A desenrolar o cordão de tricotin com cuidado...",
    "Escolhendo o melhor ponto de bordado para as folhas...",
    "A colocar os olhos de segurança no amigurumi...",
    "Desenrolando o arame galvanizado para o molde...",
    "Suavizando as curvas da letra cursiva no tricotin...",
    "A calcular a quantidade de meadas para o gráfico...",
    "Encaixando o tecido no bastidor de madeira...",
    "Passando a ferro o tecido para tirar os vincos...",
    "A dar o nó francês com toda a paciência...",
    "Pintando o gráfico com pontos e linhas...",
    "Verificando se a tensão do ponto de crochê está certa...",
    "Costurando a etiqueta da marca na peça final...",
    "A alinhar as réguas de alfaiate na mesa de corte...",
    "Cortando as sobrinhas de linha com a tesoura de garça...",
    "Medindo o contorno com a fita métrica digital...",
    "A tecer memórias com cada ponto e carreira...",
    "Preparando a encomenda com projetos finalizados...",
  ],
  en: [
    "Cutting the fabric for sewing...",
    "Threading the needle for stitching...",
    "Sorting yarn balls by colour...",
    "Picking the perfect needle size for the project...",
    "Adjusting the thread tension on the knitting spool...",
    "Counting the amigurumi stitches...",
    "Tracing the freehand embroidery outline...",
    "Shaping the wire for the next i-cord piece...",
    "Preparing the cross-stitch skein...",
    "Stuffing the amigurumi with love and fibrefill...",
    "Drawing the curves of the sewing pattern...",
    "Counting little crosses on the Aida fabric...",
    "Transferring the design onto the linen...",
    "Warming up the hands for knitting...",
    "Choosing the perfect colour palette...",
    "Winding the bobbin with sewing thread...",
    "Undoing a stubborn knot in the yarn...",
    "Finishing the last row of the project...",
    "Setting up the hoop to start embroidering...",
    "Aligning the bias on the fabric edge...",
    "Closing the invisible stitches on the amigurumi...",
    "Calculating the centimetres of wire needed...",
    "Sketching a new crochet recipe...",
    "Sorting the thread box by codes...",
    "Adjusting the sewing machine stitch...",
    "Levelling the calligraphy guide for the i-cord...",
    "Checking the DMC codes in stock...",
    "Tying the final knot on the embroidery...",
    "Stretching the fabric nice and firm...",
    "Weaving magic with threads and needles...",
    "Hiding the thread end for a flawless finish...",
    "Bringing the design to life with cross-stitch...",
    "Pinning the pattern to the fabric with precision...",
    "Unrolling the i-cord with care...",
    "Choosing the best embroidery stitch for the leaves...",
    "Fitting the safety eyes on the amigurumi...",
    "Unwinding the galvanised wire for the mould...",
    "Smoothing the curves of the cursive i-cord letter...",
    "Calculating how many skeins the chart needs...",
    "Fitting the fabric into the wooden hoop...",
    "Ironing the fabric to smooth the creases...",
    "Tying a french knot with all the patience...",
    "Painting the chart with dots and lines...",
    "Checking that the crochet tension is just right...",
    "Sewing the brand label onto the finished piece...",
    "Aligning the tailor's rulers on the cutting table...",
    "Trimming the thread tails with the stork scissors...",
    "Measuring the outline with the digital tape...",
    "Weaving memories with every stitch and row...",
    "Preparing the order with the finished projects...",
  ],
  es: [
    "Recortando la tela para coser...",
    "Enhebrando el hilo en la aguja de coser...",
    "Organizando ovillos de varios colores...",
    "Buscando el tamaño ideal de aguja para el proyecto...",
    "Ajustando la tensión del hilo en el tricotín...",
    "Contando los puntos del amigurumi...",
    "Contorneando el trazo del bordado libre...",
    "Moldeando el alambre para el próximo tricotín...",
    "Preparando la madeja de punto de cruz...",
    "Rellenando el amigurumi con amor y fibra...",
    "Dibujando las curvas del patrón de costura...",
    "Contando crucecitas en la tela Aida...",
    "Pasando el dibujo al lino...",
    "Calentando las manos para tejer...",
    "Eligiendo la paleta de colores perfecta...",
    "Llenando la bobina con el hilo de coser...",
    "Deshaciendo un nudo ciego en el ovillo...",
    "Terminando la última vuelta del proyecto...",
    "Preparando el bastidor para empezar a bordar...",
    "Alineando el bies en el borde de la tela...",
    "Cerrando los puntos invisibles del amigurumi...",
    "Calculando los centímetros de alambre necesarios...",
    "Esbozando una nueva receta de crochet...",
    "Organizando la cajita de madejas por códigos...",
    "Ajustando el punto de la máquina de coser...",
    "Nivelando la pauta de caligrafía para el tricotín...",
    "Verificando los códigos DMC en el stock...",
    "Dando el nudo final para fijar el bordado...",
    "Tensando la tela para que quede bien firme...",
    "Creando magia con líneas, hilos y agujas...",
    "Escondiendo la punta del hilo para un acabado perfecto...",
    "Dando vida al diseño con el punto de cruz...",
    "Alfilerando el patrón a la tela con precisión...",
    "Desenrollando el cordón de tricotín con cuidado...",
    "Eligiendo el mejor punto de bordado para las hojas...",
    "Colocando los ojos de seguridad en el amigurumi...",
    "Desenrollando el alambre galvanizado para el molde...",
    "Suavizando las curvas de la letra cursiva del tricotín...",
    "Calculando la cantidad de madejas para el gráfico...",
    "Encajando la tela en el bastidor de madera...",
    "Planchando la tela para quitar las arrugas...",
    "Haciendo el nudo francés con toda la paciencia...",
    "Pintando el gráfico con puntos y líneas...",
    "Comprobando si la tensión del crochet es la correcta...",
    "Cosiendo la etiqueta de la marca en la pieza final...",
    "Alineando las reglas de sastre en la mesa de corte...",
    "Cortando las hebras sobrantes con las tijeras de garza...",
    "Midiendo el contorno con la cinta métrica digital...",
    "Tejiendo recuerdos con cada punto y vuelta...",
    "Preparando el pedido con los proyectos finalizados...",
  ],
  fr: [
    "Découpe du tissu pour la couture...",
    "Enfilage du fil dans l'aiguille à coudre...",
    "Tri des pelotes de différentes couleurs...",
    "Choix de la taille d'aiguille idéale pour le projet...",
    "Ajustement de la tension du fil sur le tricotin...",
    "Comptage des mailles de l'amigurumi...",
    "Tracé du contour de la broderie libre...",
    "Modelage du fil de fer pour le prochain tricotin...",
    "Préparation de l'écheveau pour le point de croix...",
    "Rembourrage de l'amigurumi avec amour et ouate...",
    "Dessin des courbes du patron de couture...",
    "Comptage des petites croix sur la toile Aida...",
    "Report du dessin sur le lin...",
    "Échauffement des mains pour tricoter...",
    "Choix de la palette de couleurs parfaite...",
    "Remplissage de la canette avec le fil à coudre...",
    "Défaire un nœud serré dans la pelote...",
    "Terminer le dernier rang du projet...",
    "Préparation du tambour pour commencer à broder...",
    "Alignement du biais sur le bord du tissu...",
    "Fermeture des mailles invisibles de l'amigurumi...",
    "Calcul des centimètres de fil de fer nécessaires...",
    "Croquis d'une nouvelle recette de crochet...",
    "Tri de la boîte d'écheveaux par codes...",
    "Réglage du point de la machine à coudre...",
    "Nivellement de la réglure de calligraphie pour le tricotin...",
    "Vérification des codes DMC en stock...",
    "Nœud final pour fixer la broderie...",
    "Tension du tissu pour qu'il soit bien ferme...",
    "Création de magie avec fils et aiguilles...",
    "Dissimulation de la pointe du fil pour une finition parfaite...",
    "Donner vie au dessin grâce au point de croix...",
    "Épinglage du patron sur le tissu avec précision...",
    "Déroulage du cordon de tricotin avec soin...",
    "Choix du meilleur point de broderie pour les feuilles...",
    "Pose des yeux de sécurité sur l'amigurumi...",
    "Déroulage du fil galvanisé pour le moule...",
    "Adoucir les courbes de la lettre cursive en tricotin...",
    "Calcul du nombre d'écheveaux pour le diagramme...",
    "Insertion du tissu dans le tambour en bois...",
    "Repassage du tissu pour effacer les plis...",
    "Réalisation du nœud français avec toute la patience...",
    "Coloriage du diagramme avec points et lignes...",
    "Vérification de la tension du crochet...",
    "Couture de l'étiquette de marque sur la pièce finale...",
    "Alignement des règles de tailleur sur la table de coupe...",
    "Coupe des fils qui dépassent avec les ciseaux cigogne...",
    "Mesure du contour avec le mètre ruban numérique...",
    "Tisser des souvenirs à chaque point et chaque rang...",
    "Préparation de la commande avec les projets terminés...",
  ],
  de: [
    "Stoff zum Nähen zuschneiden...",
    "Faden in die Nähnadel einfädeln...",
    "Wollknäuel nach Farben sortieren...",
    "Die ideale Nadelgröße für das Projekt suchen...",
    "Fadenspannung am Strickliesl einstellen...",
    "Maschen des Amigurumi zählen...",
    "Konturen der freien Stickerei nachziehen...",
    "Draht für das nächste Strickliesl biegen...",
    "Strang für den Kreuzstich vorbereiten...",
    "Amigurumi mit Liebe und Füllwatte stopfen...",
    "Kurven des Schnittmusters zeichnen...",
    "Kreuzchen auf dem Aida-Stoff zählen...",
    "Motiv auf das Leinen übertragen...",
    "Hände zum Stricken aufwärmen...",
    "Die perfekte Farbpalette wählen...",
    "Spule mit Nähfaden aufwickeln...",
    "Einen festen Knoten im Knäuel lösen...",
    "Letzte Reihe des Projekts beenden...",
    "Stickrahmen zum Sticken vorbereiten...",
    "Schrägband an der Stoffkante ausrichten...",
    "Unsichtbare Maschen am Amigurumi schließen...",
    "Benötigte Drahtlänge in cm berechnen...",
    "Neues Häkelrezept entwerfen...",
    "Garnbox nach Codes sortieren...",
    "Stich an der Nähmaschine einstellen...",
    "Kalligrafie-Linien für das Strickliesl ausrichten...",
    "DMC-Codes im Lager prüfen...",
    "Letzten Knoten zur Sicherung der Stickerei machen...",
    "Stoff schön straff spannen...",
    "Mit Fäden und Nadeln Magie weben...",
    "Fadenende für ein perfektes Finish verstecken...",
    "Motiv mit Kreuzstich zum Leben erwecken...",
    "Schnittmuster präzise am Stoff feststecken...",
    "Strickliesl-Kordel vorsichtig abrollen...",
    "Besten Stickstich für die Blätter auswählen...",
    "Sicherheitsaugen am Amigurumi einsetzen...",
    "Verzinkten Draht für die Form abwickeln...",
    "Kurven des Schreibschrift-Strickliesl glätten...",
    "Anzahl der Stränge für das Diagramm berechnen...",
    "Stoff in den Holzrahmen einspannen...",
    "Stoff bügeln, um die Falten zu glätten...",
    "Französischen Knoten mit viel Geduld machen...",
    "Diagramm mit Punkten und Linien einfärben...",
    "Spannung des Häkelstichs prüfen...",
    "Markenetikett an das fertige Stück nähen...",
    "Schneiderlineale auf dem Zuschneidetisch ausrichten...",
    "Fadenenden mit der Storchenschere abschneiden...",
    "Umriss mit dem digitalen Maßband messen...",
    "Erinnerungen mit jeder Masche und Reihe weben...",
    "Bestellung mit fertigen Projekten vorbereiten...",
  ],
  it: [
    "Tagliando il tessuto per cucire...",
    "Infilando il filo nell'ago da cucito...",
    "Organizzando i gomitoli di vari colori...",
    "Cercando la misura ideale dell'ago per il progetto...",
    "Regolando la tensione del filo sul tricotin...",
    "Contando i punti dell'amigurumi...",
    "Ricalcando il tratto del ricamo libero...",
    "Modellando il filo di ferro per il prossimo tricotin...",
    "Preparando la matassa per il punto croce...",
    "Riempiendo l'amigurumi con amore e ovatta...",
    "Disegnando le curve del cartamodello...",
    "Contando le crocette sulla tela Aida...",
    "Trasferendo il disegno sul lino...",
    "Riscaldando le mani per lavorare a maglia...",
    "Scegliendo la palette di colori perfetta...",
    "Riempiendo la spolina con il filo da cucito...",
    "Sciogliendo un nodo cieco nel gomitolo...",
    "Terminando l'ultimo giro del progetto...",
    "Preparando il telaio per iniziare a ricamare...",
    "Allineando lo sbieco sul bordo del tessuto...",
    "Chiudendo i punti invisibili dell'amigurumi...",
    "Calcolando i centimetri di filo necessari...",
    "Abbozzando una nuova ricetta all'uncinetto...",
    "Organizzando la scatola delle matasse per codice...",
    "Regolando il punto della macchina da cucire...",
    "Livellando la riga di calligrafia per il tricotin...",
    "Verificando i codici DMC in magazzino...",
    "Facendo il nodo finale per fissare il ricamo...",
    "Tendendo bene il tessuto...",
    "Creando magia con fili e aghi...",
    "Nascondendo la punta del filo per una finitura perfetta...",
    "Dando vita al disegno con il punto croce...",
    "Appuntando il cartamodello al tessuto con precisione...",
    "Srotolando il cordoncino di tricotin con cura...",
    "Scegliendo il miglior punto di ricamo per le foglie...",
    "Mettendo gli occhi di sicurezza sull'amigurumi...",
    "Srotolando il filo zincato per la sagoma...",
    "Ammorbidendo le curve della lettera in corsivo del tricotin...",
    "Calcolando il numero di matasse per il grafico...",
    "Inserendo il tessuto nel telaio di legno...",
    "Stirando il tessuto per togliere le pieghe...",
    "Facendo il nodo francese con tutta la pazienza...",
    "Colorando il grafico con punti e linee...",
    "Verificando che la tensione dell'uncinetto sia giusta...",
    "Cucendo l'etichetta del marchio sul pezzo finito...",
    "Allineando i righelli da sarto sul tavolo da taglio...",
    "Tagliando i fili in eccesso con le forbici cicogna...",
    "Misurando il contorno con il metro digitale...",
    "Tessendo ricordi con ogni punto e giro...",
    "Preparando l'ordine con i progetti finiti...",
  ],
};