/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as TraducoesRouteImport } from './routes/traducoes'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SincronizacaoRouteImport } from './routes/sincronizacao'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as ProjetoPersonalizadoRouteImport } from './routes/projeto-personalizado'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PerfilNegocioRouteImport } from './routes/perfil-negocio'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as MoodboardsRouteImport } from './routes/moodboards'
import { Route as ModulosRouteImport } from './routes/modulos'
import { Route as MarketingCampanhasRouteImport } from './routes/marketing-campanhas'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as ListaComprasRouteImport } from './routes/lista-compras'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as IdiomaRouteImport } from './routes/idioma'
import { Route as HorasRouteImport } from './routes/horas'
import { Route as HistoricoFaturasRouteImport } from './routes/historico-faturas'
import { Route as GestaoFornecedoresRouteImport } from './routes/gestao-fornecedores'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FicheirosDigitaisRouteImport } from './routes/ficheiros-digitais'
import { Route as FaturacaoRouteImport } from './routes/faturacao'
import { Route as EtsyAuditoriaRouteImport } from './routes/etsy-auditoria'
import { Route as EtsyRouteImport } from './routes/etsy'
import { Route as EtiquetasRouteImport } from './routes/etiquetas'
import { Route as EstadoEncomendasRouteImport } from './routes/estado-encomendas'
import { Route as EncomendasRouteImport } from './routes/encomendas'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as DesignRouteImport } from './routes/design'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as CrescimentoRouteImport } from './routes/crescimento'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CashflowRouteImport } from './routes/cashflow'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoodboardsIdRouteImport } from './routes/moodboards.$id'
import { Route as ApiPublicWebhooksWhatsappRouteImport } from './routes/api/public/webhooks/whatsapp'
import { Route as ApiPublicWebhooksPendingRouteImport } from './routes/api/public/webhooks/pending'
import { Route as ApiPublicWebhooksEtsyRouteImport } from './routes/api/public/webhooks/etsy'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const TraducoesRoute = TraducoesRouteImport.update({
  id: '/traducoes',
  path: '/traducoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SincronizacaoRoute = SincronizacaoRouteImport.update({
  id: '/sincronizacao',
  path: '/sincronizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoPersonalizadoRoute = ProjetoPersonalizadoRouteImport.update({
  id: '/projeto-personalizado',
  path: '/projeto-personalizado',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilNegocioRoute = PerfilNegocioRouteImport.update({
  id: '/perfil-negocio',
  path: '/perfil-negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodboardsRoute = MoodboardsRouteImport.update({
  id: '/moodboards',
  path: '/moodboards',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosRoute = ModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCampanhasRoute = MarketingCampanhasRouteImport.update({
  id: '/marketing-campanhas',
  path: '/marketing-campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaComprasRoute = ListaComprasRouteImport.update({
  id: '/lista-compras',
  path: '/lista-compras',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const IdiomaRoute = IdiomaRouteImport.update({
  id: '/idioma',
  path: '/idioma',
  getParentRoute: () => rootRouteImport,
} as any)
const HorasRoute = HorasRouteImport.update({
  id: '/horas',
  path: '/horas',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoFaturasRoute = HistoricoFaturasRouteImport.update({
  id: '/historico-faturas',
  path: '/historico-faturas',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoFornecedoresRoute = GestaoFornecedoresRouteImport.update({
  id: '/gestao-fornecedores',
  path: '/gestao-fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FicheirosDigitaisRoute = FicheirosDigitaisRouteImport.update({
  id: '/ficheiros-digitais',
  path: '/ficheiros-digitais',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturacaoRoute = FaturacaoRouteImport.update({
  id: '/faturacao',
  path: '/faturacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EtsyAuditoriaRoute = EtsyAuditoriaRouteImport.update({
  id: '/etsy-auditoria',
  path: '/etsy-auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const EtsyRoute = EtsyRouteImport.update({
  id: '/etsy',
  path: '/etsy',
  getParentRoute: () => rootRouteImport,
} as any)
const EtiquetasRoute = EtiquetasRouteImport.update({
  id: '/etiquetas',
  path: '/etiquetas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadoEncomendasRoute = EstadoEncomendasRouteImport.update({
  id: '/estado-encomendas',
  path: '/estado-encomendas',
  getParentRoute: () => rootRouteImport,
} as any)
const EncomendasRoute = EncomendasRouteImport.update({
  id: '/encomendas',
  path: '/encomendas',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const CrescimentoRoute = CrescimentoRouteImport.update({
  id: '/crescimento',
  path: '/crescimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CashflowRoute = CashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodboardsIdRoute = MoodboardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MoodboardsRoute,
} as any)
const ApiPublicWebhooksWhatsappRoute =
  ApiPublicWebhooksWhatsappRouteImport.update({
    id: '/api/public/webhooks/whatsapp',
    path: '/api/public/webhooks/whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksPendingRoute =
  ApiPublicWebhooksPendingRouteImport.update({
    id: '/api/public/webhooks/pending',
    path: '/api/public/webhooks/pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksEtsyRoute = ApiPublicWebhooksEtsyRouteImport.update({
  id: '/api/public/webhooks/etsy',
  path: '/api/public/webhooks/etsy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/assistente': typeof AssistenteRoute
  '/auditoria': typeof AuditoriaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calculadora': typeof CalculadoraRoute
  '/calendario': typeof CalendarioRoute
  '/cashflow': typeof CashflowRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contacto': typeof ContactoRoute
  '/contas': typeof ContasRoute
  '/crescimento': typeof CrescimentoRoute
  '/cursos': typeof CursosRoute
  '/design': typeof DesignRoute
  '/despesas': typeof DespesasRoute
  '/encomendas': typeof EncomendasRoute
  '/estado-encomendas': typeof EstadoEncomendasRoute
  '/etiquetas': typeof EtiquetasRoute
  '/etsy': typeof EtsyRoute
  '/etsy-auditoria': typeof EtsyAuditoriaRoute
  '/faturacao': typeof FaturacaoRoute
  '/ficheiros-digitais': typeof FicheirosDigitaisRoute
  '/fornecedores': typeof FornecedoresRoute
  '/gestao-fornecedores': typeof GestaoFornecedoresRoute
  '/historico-faturas': typeof HistoricoFaturasRoute
  '/horas': typeof HorasRoute
  '/idioma': typeof IdiomaRoute
  '/instagram': typeof InstagramRoute
  '/lista-compras': typeof ListaComprasRoute
  '/marketing': typeof MarketingRoute
  '/marketing-campanhas': typeof MarketingCampanhasRoute
  '/modulos': typeof ModulosRoute
  '/moodboards': typeof MoodboardsRouteWithChildren
  '/notas': typeof NotasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil-negocio': typeof PerfilNegocioRoute
  '/portfolio': typeof PortfolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/projeto-personalizado': typeof ProjetoPersonalizadoRoute
  '/projetos': typeof ProjetosRoute
  '/sincronizacao': typeof SincronizacaoRoute
  '/stock': typeof StockRoute
  '/todo': typeof TodoRoute
  '/traducoes': typeof TraducoesRoute
  '/vendas': typeof VendasRoute
  '/whatsapp': typeof WhatsappRoute
  '/moodboards/$id': typeof MoodboardsIdRoute
  '/api/public/webhooks/etsy': typeof ApiPublicWebhooksEtsyRoute
  '/api/public/webhooks/pending': typeof ApiPublicWebhooksPendingRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/assistente': typeof AssistenteRoute
  '/auditoria': typeof AuditoriaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calculadora': typeof CalculadoraRoute
  '/calendario': typeof CalendarioRoute
  '/cashflow': typeof CashflowRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contacto': typeof ContactoRoute
  '/contas': typeof ContasRoute
  '/crescimento': typeof CrescimentoRoute
  '/cursos': typeof CursosRoute
  '/design': typeof DesignRoute
  '/despesas': typeof DespesasRoute
  '/encomendas': typeof EncomendasRoute
  '/estado-encomendas': typeof EstadoEncomendasRoute
  '/etiquetas': typeof EtiquetasRoute
  '/etsy': typeof EtsyRoute
  '/etsy-auditoria': typeof EtsyAuditoriaRoute
  '/faturacao': typeof FaturacaoRoute
  '/ficheiros-digitais': typeof FicheirosDigitaisRoute
  '/fornecedores': typeof FornecedoresRoute
  '/gestao-fornecedores': typeof GestaoFornecedoresRoute
  '/historico-faturas': typeof HistoricoFaturasRoute
  '/horas': typeof HorasRoute
  '/idioma': typeof IdiomaRoute
  '/instagram': typeof InstagramRoute
  '/lista-compras': typeof ListaComprasRoute
  '/marketing': typeof MarketingRoute
  '/marketing-campanhas': typeof MarketingCampanhasRoute
  '/modulos': typeof ModulosRoute
  '/moodboards': typeof MoodboardsRouteWithChildren
  '/notas': typeof NotasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil-negocio': typeof PerfilNegocioRoute
  '/portfolio': typeof PortfolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/projeto-personalizado': typeof ProjetoPersonalizadoRoute
  '/projetos': typeof ProjetosRoute
  '/sincronizacao': typeof SincronizacaoRoute
  '/stock': typeof StockRoute
  '/todo': typeof TodoRoute
  '/traducoes': typeof TraducoesRoute
  '/vendas': typeof VendasRoute
  '/whatsapp': typeof WhatsappRoute
  '/moodboards/$id': typeof MoodboardsIdRoute
  '/api/public/webhooks/etsy': typeof ApiPublicWebhooksEtsyRoute
  '/api/public/webhooks/pending': typeof ApiPublicWebhooksPendingRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/assistente': typeof AssistenteRoute
  '/auditoria': typeof AuditoriaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calculadora': typeof CalculadoraRoute
  '/calendario': typeof CalendarioRoute
  '/cashflow': typeof CashflowRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contacto': typeof ContactoRoute
  '/contas': typeof ContasRoute
  '/crescimento': typeof CrescimentoRoute
  '/cursos': typeof CursosRoute
  '/design': typeof DesignRoute
  '/despesas': typeof DespesasRoute
  '/encomendas': typeof EncomendasRoute
  '/estado-encomendas': typeof EstadoEncomendasRoute
  '/etiquetas': typeof EtiquetasRoute
  '/etsy': typeof EtsyRoute
  '/etsy-auditoria': typeof EtsyAuditoriaRoute
  '/faturacao': typeof FaturacaoRoute
  '/ficheiros-digitais': typeof FicheirosDigitaisRoute
  '/fornecedores': typeof FornecedoresRoute
  '/gestao-fornecedores': typeof GestaoFornecedoresRoute
  '/historico-faturas': typeof HistoricoFaturasRoute
  '/horas': typeof HorasRoute
  '/idioma': typeof IdiomaRoute
  '/instagram': typeof InstagramRoute
  '/lista-compras': typeof ListaComprasRoute
  '/marketing': typeof MarketingRoute
  '/marketing-campanhas': typeof MarketingCampanhasRoute
  '/modulos': typeof ModulosRoute
  '/moodboards': typeof MoodboardsRouteWithChildren
  '/notas': typeof NotasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil-negocio': typeof PerfilNegocioRoute
  '/portfolio': typeof PortfolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/projeto-personalizado': typeof ProjetoPersonalizadoRoute
  '/projetos': typeof ProjetosRoute
  '/sincronizacao': typeof SincronizacaoRoute
  '/stock': typeof StockRoute
  '/todo': typeof TodoRoute
  '/traducoes': typeof TraducoesRoute
  '/vendas': typeof VendasRoute
  '/whatsapp': typeof WhatsappRoute
  '/moodboards/$id': typeof MoodboardsIdRoute
  '/api/public/webhooks/etsy': typeof ApiPublicWebhooksEtsyRoute
  '/api/public/webhooks/pending': typeof ApiPublicWebhooksPendingRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/assistente'
    | '/auditoria'
    | '/biblioteca'
    | '/calculadora'
    | '/calendario'
    | '/cashflow'
    | '/catalogo'
    | '/clientes'
    | '/configuracoes'
    | '/contacto'
    | '/contas'
    | '/crescimento'
    | '/cursos'
    | '/design'
    | '/despesas'
    | '/encomendas'
    | '/estado-encomendas'
    | '/etiquetas'
    | '/etsy'
    | '/etsy-auditoria'
    | '/faturacao'
    | '/ficheiros-digitais'
    | '/fornecedores'
    | '/gestao-fornecedores'
    | '/historico-faturas'
    | '/horas'
    | '/idioma'
    | '/instagram'
    | '/lista-compras'
    | '/marketing'
    | '/marketing-campanhas'
    | '/modulos'
    | '/moodboards'
    | '/notas'
    | '/notificacoes'
    | '/onboarding'
    | '/perfil-negocio'
    | '/portfolio'
    | '/privacidade'
    | '/projeto-personalizado'
    | '/projetos'
    | '/sincronizacao'
    | '/stock'
    | '/todo'
    | '/traducoes'
    | '/vendas'
    | '/whatsapp'
    | '/moodboards/$id'
    | '/api/public/webhooks/etsy'
    | '/api/public/webhooks/pending'
    | '/api/public/webhooks/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/assistente'
    | '/auditoria'
    | '/biblioteca'
    | '/calculadora'
    | '/calendario'
    | '/cashflow'
    | '/catalogo'
    | '/clientes'
    | '/configuracoes'
    | '/contacto'
    | '/contas'
    | '/crescimento'
    | '/cursos'
    | '/design'
    | '/despesas'
    | '/encomendas'
    | '/estado-encomendas'
    | '/etiquetas'
    | '/etsy'
    | '/etsy-auditoria'
    | '/faturacao'
    | '/ficheiros-digitais'
    | '/fornecedores'
    | '/gestao-fornecedores'
    | '/historico-faturas'
    | '/horas'
    | '/idioma'
    | '/instagram'
    | '/lista-compras'
    | '/marketing'
    | '/marketing-campanhas'
    | '/modulos'
    | '/moodboards'
    | '/notas'
    | '/notificacoes'
    | '/onboarding'
    | '/perfil-negocio'
    | '/portfolio'
    | '/privacidade'
    | '/projeto-personalizado'
    | '/projetos'
    | '/sincronizacao'
    | '/stock'
    | '/todo'
    | '/traducoes'
    | '/vendas'
    | '/whatsapp'
    | '/moodboards/$id'
    | '/api/public/webhooks/etsy'
    | '/api/public/webhooks/pending'
    | '/api/public/webhooks/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/assistente'
    | '/auditoria'
    | '/biblioteca'
    | '/calculadora'
    | '/calendario'
    | '/cashflow'
    | '/catalogo'
    | '/clientes'
    | '/configuracoes'
    | '/contacto'
    | '/contas'
    | '/crescimento'
    | '/cursos'
    | '/design'
    | '/despesas'
    | '/encomendas'
    | '/estado-encomendas'
    | '/etiquetas'
    | '/etsy'
    | '/etsy-auditoria'
    | '/faturacao'
    | '/ficheiros-digitais'
    | '/fornecedores'
    | '/gestao-fornecedores'
    | '/historico-faturas'
    | '/horas'
    | '/idioma'
    | '/instagram'
    | '/lista-compras'
    | '/marketing'
    | '/marketing-campanhas'
    | '/modulos'
    | '/moodboards'
    | '/notas'
    | '/notificacoes'
    | '/onboarding'
    | '/perfil-negocio'
    | '/portfolio'
    | '/privacidade'
    | '/projeto-personalizado'
    | '/projetos'
    | '/sincronizacao'
    | '/stock'
    | '/todo'
    | '/traducoes'
    | '/vendas'
    | '/whatsapp'
    | '/moodboards/$id'
    | '/api/public/webhooks/etsy'
    | '/api/public/webhooks/pending'
    | '/api/public/webhooks/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  AssistenteRoute: typeof AssistenteRoute
  AuditoriaRoute: typeof AuditoriaRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CalculadoraRoute: typeof CalculadoraRoute
  CalendarioRoute: typeof CalendarioRoute
  CashflowRoute: typeof CashflowRoute
  CatalogoRoute: typeof CatalogoRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContactoRoute: typeof ContactoRoute
  ContasRoute: typeof ContasRoute
  CrescimentoRoute: typeof CrescimentoRoute
  CursosRoute: typeof CursosRoute
  DesignRoute: typeof DesignRoute
  DespesasRoute: typeof DespesasRoute
  EncomendasRoute: typeof EncomendasRoute
  EstadoEncomendasRoute: typeof EstadoEncomendasRoute
  EtiquetasRoute: typeof EtiquetasRoute
  EtsyRoute: typeof EtsyRoute
  EtsyAuditoriaRoute: typeof EtsyAuditoriaRoute
  FaturacaoRoute: typeof FaturacaoRoute
  FicheirosDigitaisRoute: typeof FicheirosDigitaisRoute
  FornecedoresRoute: typeof FornecedoresRoute
  GestaoFornecedoresRoute: typeof GestaoFornecedoresRoute
  HistoricoFaturasRoute: typeof HistoricoFaturasRoute
  HorasRoute: typeof HorasRoute
  IdiomaRoute: typeof IdiomaRoute
  InstagramRoute: typeof InstagramRoute
  ListaComprasRoute: typeof ListaComprasRoute
  MarketingRoute: typeof MarketingRoute
  MarketingCampanhasRoute: typeof MarketingCampanhasRoute
  ModulosRoute: typeof ModulosRoute
  MoodboardsRoute: typeof MoodboardsRouteWithChildren
  NotasRoute: typeof NotasRoute
  NotificacoesRoute: typeof NotificacoesRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilNegocioRoute: typeof PerfilNegocioRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProjetoPersonalizadoRoute: typeof ProjetoPersonalizadoRoute
  ProjetosRoute: typeof ProjetosRoute
  SincronizacaoRoute: typeof SincronizacaoRoute
  StockRoute: typeof StockRoute
  TodoRoute: typeof TodoRoute
  TraducoesRoute: typeof TraducoesRoute
  VendasRoute: typeof VendasRoute
  WhatsappRoute: typeof WhatsappRoute
  ApiPublicWebhooksEtsyRoute: typeof ApiPublicWebhooksEtsyRoute
  ApiPublicWebhooksPendingRoute: typeof ApiPublicWebhooksPendingRoute
  ApiPublicWebhooksWhatsappRoute: typeof ApiPublicWebhooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traducoes': {
      id: '/traducoes'
      path: '/traducoes'
      fullPath: '/traducoes'
      preLoaderRoute: typeof TraducoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sincronizacao': {
      id: '/sincronizacao'
      path: '/sincronizacao'
      fullPath: '/sincronizacao'
      preLoaderRoute: typeof SincronizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto-personalizado': {
      id: '/projeto-personalizado'
      path: '/projeto-personalizado'
      fullPath: '/projeto-personalizado'
      preLoaderRoute: typeof ProjetoPersonalizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-negocio': {
      id: '/perfil-negocio'
      path: '/perfil-negocio'
      fullPath: '/perfil-negocio'
      preLoaderRoute: typeof PerfilNegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moodboards': {
      id: '/moodboards'
      path: '/moodboards'
      fullPath: '/moodboards'
      preLoaderRoute: typeof MoodboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos': {
      id: '/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof ModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-campanhas': {
      id: '/marketing-campanhas'
      path: '/marketing-campanhas'
      fullPath: '/marketing-campanhas'
      preLoaderRoute: typeof MarketingCampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista-compras': {
      id: '/lista-compras'
      path: '/lista-compras'
      fullPath: '/lista-compras'
      preLoaderRoute: typeof ListaComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idioma': {
      id: '/idioma'
      path: '/idioma'
      fullPath: '/idioma'
      preLoaderRoute: typeof IdiomaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horas': {
      id: '/horas'
      path: '/horas'
      fullPath: '/horas'
      preLoaderRoute: typeof HorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico-faturas': {
      id: '/historico-faturas'
      path: '/historico-faturas'
      fullPath: '/historico-faturas'
      preLoaderRoute: typeof HistoricoFaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-fornecedores': {
      id: '/gestao-fornecedores'
      path: '/gestao-fornecedores'
      fullPath: '/gestao-fornecedores'
      preLoaderRoute: typeof GestaoFornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ficheiros-digitais': {
      id: '/ficheiros-digitais'
      path: '/ficheiros-digitais'
      fullPath: '/ficheiros-digitais'
      preLoaderRoute: typeof FicheirosDigitaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturacao': {
      id: '/faturacao'
      path: '/faturacao'
      fullPath: '/faturacao'
      preLoaderRoute: typeof FaturacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etsy-auditoria': {
      id: '/etsy-auditoria'
      path: '/etsy-auditoria'
      fullPath: '/etsy-auditoria'
      preLoaderRoute: typeof EtsyAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etsy': {
      id: '/etsy'
      path: '/etsy'
      fullPath: '/etsy'
      preLoaderRoute: typeof EtsyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etiquetas': {
      id: '/etiquetas'
      path: '/etiquetas'
      fullPath: '/etiquetas'
      preLoaderRoute: typeof EtiquetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estado-encomendas': {
      id: '/estado-encomendas'
      path: '/estado-encomendas'
      fullPath: '/estado-encomendas'
      preLoaderRoute: typeof EstadoEncomendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encomendas': {
      id: '/encomendas'
      path: '/encomendas'
      fullPath: '/encomendas'
      preLoaderRoute: typeof EncomendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crescimento': {
      id: '/crescimento'
      path: '/crescimento'
      fullPath: '/crescimento'
      preLoaderRoute: typeof CrescimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashflow': {
      id: '/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof CashflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moodboards/$id': {
      id: '/moodboards/$id'
      path: '/$id'
      fullPath: '/moodboards/$id'
      preLoaderRoute: typeof MoodboardsIdRouteImport
      parentRoute: typeof MoodboardsRoute
    }
    '/api/public/webhooks/whatsapp': {
      id: '/api/public/webhooks/whatsapp'
      path: '/api/public/webhooks/whatsapp'
      fullPath: '/api/public/webhooks/whatsapp'
      preLoaderRoute: typeof ApiPublicWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/pending': {
      id: '/api/public/webhooks/pending'
      path: '/api/public/webhooks/pending'
      fullPath: '/api/public/webhooks/pending'
      preLoaderRoute: typeof ApiPublicWebhooksPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/etsy': {
      id: '/api/public/webhooks/etsy'
      path: '/api/public/webhooks/etsy'
      fullPath: '/api/public/webhooks/etsy'
      preLoaderRoute: typeof ApiPublicWebhooksEtsyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MoodboardsRouteChildren {
  MoodboardsIdRoute: typeof MoodboardsIdRoute
}

const MoodboardsRouteChildren: MoodboardsRouteChildren = {
  MoodboardsIdRoute: MoodboardsIdRoute,
}

const MoodboardsRouteWithChildren = MoodboardsRoute._addFileChildren(
  MoodboardsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  AssistenteRoute: AssistenteRoute,
  AuditoriaRoute: AuditoriaRoute,
  BibliotecaRoute: BibliotecaRoute,
  CalculadoraRoute: CalculadoraRoute,
  CalendarioRoute: CalendarioRoute,
  CashflowRoute: CashflowRoute,
  CatalogoRoute: CatalogoRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContactoRoute: ContactoRoute,
  ContasRoute: ContasRoute,
  CrescimentoRoute: CrescimentoRoute,
  CursosRoute: CursosRoute,
  DesignRoute: DesignRoute,
  DespesasRoute: DespesasRoute,
  EncomendasRoute: EncomendasRoute,
  EstadoEncomendasRoute: EstadoEncomendasRoute,
  EtiquetasRoute: EtiquetasRoute,
  EtsyRoute: EtsyRoute,
  EtsyAuditoriaRoute: EtsyAuditoriaRoute,
  FaturacaoRoute: FaturacaoRoute,
  FicheirosDigitaisRoute: FicheirosDigitaisRoute,
  FornecedoresRoute: FornecedoresRoute,
  GestaoFornecedoresRoute: GestaoFornecedoresRoute,
  HistoricoFaturasRoute: HistoricoFaturasRoute,
  HorasRoute: HorasRoute,
  IdiomaRoute: IdiomaRoute,
  InstagramRoute: InstagramRoute,
  ListaComprasRoute: ListaComprasRoute,
  MarketingRoute: MarketingRoute,
  MarketingCampanhasRoute: MarketingCampanhasRoute,
  ModulosRoute: ModulosRoute,
  MoodboardsRoute: MoodboardsRouteWithChildren,
  NotasRoute: NotasRoute,
  NotificacoesRoute: NotificacoesRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilNegocioRoute: PerfilNegocioRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProjetoPersonalizadoRoute: ProjetoPersonalizadoRoute,
  ProjetosRoute: ProjetosRoute,
  SincronizacaoRoute: SincronizacaoRoute,
  StockRoute: StockRoute,
  TodoRoute: TodoRoute,
  TraducoesRoute: TraducoesRoute,
  VendasRoute: VendasRoute,
  WhatsappRoute: WhatsappRoute,
  ApiPublicWebhooksEtsyRoute: ApiPublicWebhooksEtsyRoute,
  ApiPublicWebhooksPendingRoute: ApiPublicWebhooksPendingRoute,
  ApiPublicWebhooksWhatsappRoute: ApiPublicWebhooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
