/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SincronizacaoRouteImport } from './routes/sincronizacao'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as ProjetoPersonalizadoRouteImport } from './routes/projeto-personalizado'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PerfilNegocioRouteImport } from './routes/perfil-negocio'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as ListaComprasRouteImport } from './routes/lista-compras'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as IdiomaRouteImport } from './routes/idioma'
import { Route as HorasRouteImport } from './routes/horas'
import { Route as GestaoFornecedoresRouteImport } from './routes/gestao-fornecedores'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FaturacaoRouteImport } from './routes/faturacao'
import { Route as EstadoEncomendasRouteImport } from './routes/estado-encomendas'
import { Route as EncomendasRouteImport } from './routes/encomendas'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as DesignRouteImport } from './routes/design'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as CrescimentoRouteImport } from './routes/crescimento'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CashflowRouteImport } from './routes/cashflow'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as IndexRouteImport } from './routes/index'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SincronizacaoRoute = SincronizacaoRouteImport.update({
  id: '/sincronizacao',
  path: '/sincronizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoPersonalizadoRoute = ProjetoPersonalizadoRouteImport.update({
  id: '/projeto-personalizado',
  path: '/projeto-personalizado',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilNegocioRoute = PerfilNegocioRouteImport.update({
  id: '/perfil-negocio',
  path: '/perfil-negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaComprasRoute = ListaComprasRouteImport.update({
  id: '/lista-compras',
  path: '/lista-compras',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const IdiomaRoute = IdiomaRouteImport.update({
  id: '/idioma',
  path: '/idioma',
  getParentRoute: () => rootRouteImport,
} as any)
const HorasRoute = HorasRouteImport.update({
  id: '/horas',
  path: '/horas',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoFornecedoresRoute = GestaoFornecedoresRouteImport.update({
  id: '/gestao-fornecedores',
  path: '/gestao-fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturacaoRoute = FaturacaoRouteImport.update({
  id: '/faturacao',
  path: '/faturacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadoEncomendasRoute = EstadoEncomendasRouteImport.update({
  id: '/estado-encomendas',
  path: '/estado-encomendas',
  getParentRoute: () => rootRouteImport,
} as any)
const EncomendasRoute = EncomendasRouteImport.update({
  id: '/encomendas',
  path: '/encomendas',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const CrescimentoRoute = CrescimentoRouteImport.update({
  id: '/crescimento',
  path: '/crescimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CashflowRoute = CashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/assistente': typeof AssistenteRoute
  '/auditoria': typeof AuditoriaRoute
  '/calculadora': typeof CalculadoraRoute
  '/calendario': typeof CalendarioRoute
  '/cashflow': typeof CashflowRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contacto': typeof ContactoRoute
  '/contas': typeof ContasRoute
  '/crescimento': typeof CrescimentoRoute
  '/cursos': typeof CursosRoute
  '/design': typeof DesignRoute
  '/despesas': typeof DespesasRoute
  '/encomendas': typeof EncomendasRoute
  '/estado-encomendas': typeof EstadoEncomendasRoute
  '/faturacao': typeof FaturacaoRoute
  '/fornecedores': typeof FornecedoresRoute
  '/gestao-fornecedores': typeof GestaoFornecedoresRoute
  '/horas': typeof HorasRoute
  '/idioma': typeof IdiomaRoute
  '/instagram': typeof InstagramRoute
  '/lista-compras': typeof ListaComprasRoute
  '/marketing': typeof MarketingRoute
  '/perfil-negocio': typeof PerfilNegocioRoute
  '/portfolio': typeof PortfolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/projeto-personalizado': typeof ProjetoPersonalizadoRoute
  '/projetos': typeof ProjetosRoute
  '/sincronizacao': typeof SincronizacaoRoute
  '/stock': typeof StockRoute
  '/todo': typeof TodoRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/assistente': typeof AssistenteRoute
  '/auditoria': typeof AuditoriaRoute
  '/calculadora': typeof CalculadoraRoute
  '/calendario': typeof CalendarioRoute
  '/cashflow': typeof CashflowRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contacto': typeof ContactoRoute
  '/contas': typeof ContasRoute
  '/crescimento': typeof CrescimentoRoute
  '/cursos': typeof CursosRoute
  '/design': typeof DesignRoute
  '/despesas': typeof DespesasRoute
  '/encomendas': typeof EncomendasRoute
  '/estado-encomendas': typeof EstadoEncomendasRoute
  '/faturacao': typeof FaturacaoRoute
  '/fornecedores': typeof FornecedoresRoute
  '/gestao-fornecedores': typeof GestaoFornecedoresRoute
  '/horas': typeof HorasRoute
  '/idioma': typeof IdiomaRoute
  '/instagram': typeof InstagramRoute
  '/lista-compras': typeof ListaComprasRoute
  '/marketing': typeof MarketingRoute
  '/perfil-negocio': typeof PerfilNegocioRoute
  '/portfolio': typeof PortfolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/projeto-personalizado': typeof ProjetoPersonalizadoRoute
  '/projetos': typeof ProjetosRoute
  '/sincronizacao': typeof SincronizacaoRoute
  '/stock': typeof StockRoute
  '/todo': typeof TodoRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/assistente': typeof AssistenteRoute
  '/auditoria': typeof AuditoriaRoute
  '/calculadora': typeof CalculadoraRoute
  '/calendario': typeof CalendarioRoute
  '/cashflow': typeof CashflowRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contacto': typeof ContactoRoute
  '/contas': typeof ContasRoute
  '/crescimento': typeof CrescimentoRoute
  '/cursos': typeof CursosRoute
  '/design': typeof DesignRoute
  '/despesas': typeof DespesasRoute
  '/encomendas': typeof EncomendasRoute
  '/estado-encomendas': typeof EstadoEncomendasRoute
  '/faturacao': typeof FaturacaoRoute
  '/fornecedores': typeof FornecedoresRoute
  '/gestao-fornecedores': typeof GestaoFornecedoresRoute
  '/horas': typeof HorasRoute
  '/idioma': typeof IdiomaRoute
  '/instagram': typeof InstagramRoute
  '/lista-compras': typeof ListaComprasRoute
  '/marketing': typeof MarketingRoute
  '/perfil-negocio': typeof PerfilNegocioRoute
  '/portfolio': typeof PortfolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/projeto-personalizado': typeof ProjetoPersonalizadoRoute
  '/projetos': typeof ProjetosRoute
  '/sincronizacao': typeof SincronizacaoRoute
  '/stock': typeof StockRoute
  '/todo': typeof TodoRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/assistente'
    | '/auditoria'
    | '/calculadora'
    | '/calendario'
    | '/cashflow'
    | '/clientes'
    | '/configuracoes'
    | '/contacto'
    | '/contas'
    | '/crescimento'
    | '/cursos'
    | '/design'
    | '/despesas'
    | '/encomendas'
    | '/estado-encomendas'
    | '/faturacao'
    | '/fornecedores'
    | '/gestao-fornecedores'
    | '/horas'
    | '/idioma'
    | '/instagram'
    | '/lista-compras'
    | '/marketing'
    | '/perfil-negocio'
    | '/portfolio'
    | '/privacidade'
    | '/projeto-personalizado'
    | '/projetos'
    | '/sincronizacao'
    | '/stock'
    | '/todo'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/assistente'
    | '/auditoria'
    | '/calculadora'
    | '/calendario'
    | '/cashflow'
    | '/clientes'
    | '/configuracoes'
    | '/contacto'
    | '/contas'
    | '/crescimento'
    | '/cursos'
    | '/design'
    | '/despesas'
    | '/encomendas'
    | '/estado-encomendas'
    | '/faturacao'
    | '/fornecedores'
    | '/gestao-fornecedores'
    | '/horas'
    | '/idioma'
    | '/instagram'
    | '/lista-compras'
    | '/marketing'
    | '/perfil-negocio'
    | '/portfolio'
    | '/privacidade'
    | '/projeto-personalizado'
    | '/projetos'
    | '/sincronizacao'
    | '/stock'
    | '/todo'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/assistente'
    | '/auditoria'
    | '/calculadora'
    | '/calendario'
    | '/cashflow'
    | '/clientes'
    | '/configuracoes'
    | '/contacto'
    | '/contas'
    | '/crescimento'
    | '/cursos'
    | '/design'
    | '/despesas'
    | '/encomendas'
    | '/estado-encomendas'
    | '/faturacao'
    | '/fornecedores'
    | '/gestao-fornecedores'
    | '/horas'
    | '/idioma'
    | '/instagram'
    | '/lista-compras'
    | '/marketing'
    | '/perfil-negocio'
    | '/portfolio'
    | '/privacidade'
    | '/projeto-personalizado'
    | '/projetos'
    | '/sincronizacao'
    | '/stock'
    | '/todo'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  AssistenteRoute: typeof AssistenteRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CalculadoraRoute: typeof CalculadoraRoute
  CalendarioRoute: typeof CalendarioRoute
  CashflowRoute: typeof CashflowRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContactoRoute: typeof ContactoRoute
  ContasRoute: typeof ContasRoute
  CrescimentoRoute: typeof CrescimentoRoute
  CursosRoute: typeof CursosRoute
  DesignRoute: typeof DesignRoute
  DespesasRoute: typeof DespesasRoute
  EncomendasRoute: typeof EncomendasRoute
  EstadoEncomendasRoute: typeof EstadoEncomendasRoute
  FaturacaoRoute: typeof FaturacaoRoute
  FornecedoresRoute: typeof FornecedoresRoute
  GestaoFornecedoresRoute: typeof GestaoFornecedoresRoute
  HorasRoute: typeof HorasRoute
  IdiomaRoute: typeof IdiomaRoute
  InstagramRoute: typeof InstagramRoute
  ListaComprasRoute: typeof ListaComprasRoute
  MarketingRoute: typeof MarketingRoute
  PerfilNegocioRoute: typeof PerfilNegocioRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProjetoPersonalizadoRoute: typeof ProjetoPersonalizadoRoute
  ProjetosRoute: typeof ProjetosRoute
  SincronizacaoRoute: typeof SincronizacaoRoute
  StockRoute: typeof StockRoute
  TodoRoute: typeof TodoRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sincronizacao': {
      id: '/sincronizacao'
      path: '/sincronizacao'
      fullPath: '/sincronizacao'
      preLoaderRoute: typeof SincronizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto-personalizado': {
      id: '/projeto-personalizado'
      path: '/projeto-personalizado'
      fullPath: '/projeto-personalizado'
      preLoaderRoute: typeof ProjetoPersonalizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-negocio': {
      id: '/perfil-negocio'
      path: '/perfil-negocio'
      fullPath: '/perfil-negocio'
      preLoaderRoute: typeof PerfilNegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista-compras': {
      id: '/lista-compras'
      path: '/lista-compras'
      fullPath: '/lista-compras'
      preLoaderRoute: typeof ListaComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idioma': {
      id: '/idioma'
      path: '/idioma'
      fullPath: '/idioma'
      preLoaderRoute: typeof IdiomaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horas': {
      id: '/horas'
      path: '/horas'
      fullPath: '/horas'
      preLoaderRoute: typeof HorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-fornecedores': {
      id: '/gestao-fornecedores'
      path: '/gestao-fornecedores'
      fullPath: '/gestao-fornecedores'
      preLoaderRoute: typeof GestaoFornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturacao': {
      id: '/faturacao'
      path: '/faturacao'
      fullPath: '/faturacao'
      preLoaderRoute: typeof FaturacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estado-encomendas': {
      id: '/estado-encomendas'
      path: '/estado-encomendas'
      fullPath: '/estado-encomendas'
      preLoaderRoute: typeof EstadoEncomendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encomendas': {
      id: '/encomendas'
      path: '/encomendas'
      fullPath: '/encomendas'
      preLoaderRoute: typeof EncomendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crescimento': {
      id: '/crescimento'
      path: '/crescimento'
      fullPath: '/crescimento'
      preLoaderRoute: typeof CrescimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashflow': {
      id: '/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof CashflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  AssistenteRoute: AssistenteRoute,
  AuditoriaRoute: AuditoriaRoute,
  CalculadoraRoute: CalculadoraRoute,
  CalendarioRoute: CalendarioRoute,
  CashflowRoute: CashflowRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContactoRoute: ContactoRoute,
  ContasRoute: ContasRoute,
  CrescimentoRoute: CrescimentoRoute,
  CursosRoute: CursosRoute,
  DesignRoute: DesignRoute,
  DespesasRoute: DespesasRoute,
  EncomendasRoute: EncomendasRoute,
  EstadoEncomendasRoute: EstadoEncomendasRoute,
  FaturacaoRoute: FaturacaoRoute,
  FornecedoresRoute: FornecedoresRoute,
  GestaoFornecedoresRoute: GestaoFornecedoresRoute,
  HorasRoute: HorasRoute,
  IdiomaRoute: IdiomaRoute,
  InstagramRoute: InstagramRoute,
  ListaComprasRoute: ListaComprasRoute,
  MarketingRoute: MarketingRoute,
  PerfilNegocioRoute: PerfilNegocioRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProjetoPersonalizadoRoute: ProjetoPersonalizadoRoute,
  ProjetosRoute: ProjetosRoute,
  SincronizacaoRoute: SincronizacaoRoute,
  StockRoute: StockRoute,
  TodoRoute: TodoRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
